service: buggy-app
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ap-southeast-1"}
  timeout: 30

  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    EVENTS_TABLE: ${self:custom.EVENTS_TABLE}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:UpdateItem"
            - "dynamodb:PutItem"
          Resource:
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.EVENTS_TABLE}"

custom:
  EVENTS_TABLE: events-table-${self:provider.stage}

functions:
  listEvents: 
    handler: listEvents/index.handler
    name: listEvents
    package:
      individually: true
      artifact: "./dist/listEvents.zip"

resources:
  Resources:
    eventsTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.EVENTS_TABLE}
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: "S"
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: eventId
            KeyType: "HASH"
